[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Kinova Gen3 RL Pick-and-Place"
author = "Isaac Lab Project Developers"
maintainer = "Isaac Lab Project Developers"
description="Isaac Lab tasks (reach, grasp, lift-and-place) for RL pick-and-place with the Kinova Gen3 + Robotiq 2F-140"
repository = "https://github.com/IdoRaviel/kinova_isaaclab_sim2real"
keywords = ["isaaclab", "kinova", "manipulation", "reinforcement-learning", "pick-and-place"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "gen3"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"